version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: all-scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: all-scripts/start_container.sh
      timeout: 300
      runas: root
