---
apiVersion: v1
kind: Namespace
metadata:
  name: flask_api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask_api
  name: deployment-flask-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-api
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-api
    spec:
      containers:
      - image: alexwhen/docker-flask-api
        imagePullPolicy: Always
        name: flask-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: flask-api
  name: service-flask-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: flask-api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: flask-api
  name: ingress-flask-api
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-flask-api
              servicePort: 8080
